version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    links:
      - alertmanager:alertmanager
  alertmanager:
    image: "prom/alertmanager:latest"
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/ 
