---
- hosts: local
  tasks:
    - name: Get files
      get_url:
        url: "http://{{ item }}/index.html"
        dest: "/tmp/{{ item }}"
      ignore_errors: yes
      with_items:
        - server2.mylabserver.com
        - server3.mylabserver.com
        - server4.mylabserver.com
